-- Drop existing table if it exists
drop table if exists tasks;

-- Create tasks table
create table tasks (
    id bigint generated by default as identity primary key,
    text text not null,
    completed boolean default false,
    is_current boolean default false,
    timer_active boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    completed_at timestamp with time zone,
    task_type text not null default '5min',
    duration integer not null default 5
);

-- Create indexes for better query performance
create index tasks_completed_idx on tasks(completed);
create index tasks_is_current_idx on tasks(is_current);
create index tasks_created_at_idx on tasks(created_at desc);
create index tasks_task_type_idx on tasks(task_type);

-- Enable Row Level Security (RLS)
alter table tasks enable row level security;

-- Create a policy that allows all operations (for now)
create policy "Allow all operations" on tasks
    for all
    using (true)
    with check (true); 